version: '3.8'
services:
  postgres:
    container_name: giabao_postgres
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgresql
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5555:5432

volumes:
  data:
